#Author: Kai Oswald
#Source: https://dev.to/kaos/complete-cicd-for-flutter-apps-42dc

name: Build Flutter apps

on:
  push:
    branches:
      - '*'
    tags:
      - v*


jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random test

  build_android:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Build Android App
        run: flutter build apk

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: android
          path: build/app/outputs/**/*.apk

  build_ios:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: ios
          path: build/ios/iphoneos/app.ipa

  build_web:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Build web
        run: |
          flutter build web
          cd build/web
          zip -r web-app.zip .

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: web
          path: build/web/web-app.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build_android, build_ios, build_web ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          path: build/

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/**/*.apk,build/**/app.ipa,build/**/web-app.zip'

  deploy:
    if: startsWith(github.ref, 'refs/tags/v') && false # Disable deployment since no production environment is currently set up.
    needs: [ build_android, build_ios, build_web ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web
          path: build/web

#      - name: Deploy to Firebase hosting
#        uses: w9jds/firebase-action@master
#        with:
#          args: deploy --message \"${{ github.event.head_commit.message }}\" --only hosting
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  
